disabled_rules:
  - trailing_comma
line_length:
  - 200
cyclomatic_complexity:
  - 12
identifier_name:
  excluded:
    - x
    - y
    - i
    - id
    - vc
    - on
    - to
    - os
    - rx
    - me
    - ok
